### ISSUE TITLE
BUG, press and drag on elements

### ISSUE THREAD

**Issue by MewX** [sentenza/jekyll-material-design#3]
For example, on top action bar, I press on a button and drag out of it, then its effects goes weirdly.
I mean it keeps the pressed status.

![qq 20150121122348](https://cloud.githubusercontent.com/assets/5752560/5831197/5fa40782-a168-11e4-85f8-301c0be031fd.png)

**Comment by sentenza** [comment]
I updated Bootstrap and the Paper theme to their latest versions. Now, it should be fixed.
