### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by newswim** [sentenza/jekyll-material-design#4]
Can I get some pointers on adding different types of images (teaser, featured)? I don't seem to be making any progress on ciphering through the jekyll rendering engine. Lets say you wanted to add an image to one of the example posts?

I've tried  `<img src="{{ BASE_PATH }}/images/{{ page.image.featured }}">`

.. to no avail.

**Comment by sentenza** [comment]
You have to use the Jekyll syntax to add a teaser image:

```
![Jekyll Logo]({{ site.url }}/assets/images/jekyll-logo-light-solid.png)
```

See the above referenced commit and http://torre.me.uk/jekyll-material-design/lessons/2014/02/10/jekyll-intro/

**Comment by newswim** [comment]
Thanks for getting back to me!!
